services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8081
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
